In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
appearences = pd.read_csv('baseball_csv_files/appearances.csv')

In [4]:
appearences.sort_values(by=['player_id', 'year']).head(15)

,year,team_id,league_id,player_id,g_all,gs,g_batting,g_defense,g_p,g_c,...,g_2b,g_3b,g_ss,g_lf,g_cf,g_rf,g_of,g_dh,g_ph,g_pr
85713,2004,SFN,NL,aardsda01,11.0,0.0,11,11.0,11,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
87495,2006,CHN,NL,aardsda01,45.0,0.0,43,45.0,45,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
88832,2007,CHA,AL,aardsda01,25.0,0.0,2,25.0,25,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
90166,2008,BOS,AL,aardsda01,47.0,0.0,5,47.0,47,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
92486,2009,SEA,AL,aardsda01,73.0,0.0,3,73.0,73,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
93852,2010,SEA,AL,aardsda01,53.0,0.0,4,53.0,53,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
96207,2012,NYA,AL,aardsda01,1.0,0.0,0,1.0,1,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
97582,2013,NYN,NL,aardsda01,43.0,0.0,41,43.0,43,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
99466,2015,ATL,NL,aardsda01,33.0,0.0,30,33.0,33,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
37137,1954,ML1,NL,aaronha01,122.0,NaN,122,122.0,0,0,...,0,0,0,105,0,11,116,NaN,NaN,NaN
37803,1955,ML1,NL,aaronha01,153.0,NaN,153,153.0,0,0,...,27,0,0,26,0,105,126,NaN,NaN,NaN
38426,1956,ML1,NL,aaronha01,153.0,NaN,153,153.0,0,0,...,0,0,0,0,0,152,152,NaN,NaN,NaN
39047,1957,ML1,NL,aaronha01,151.0,NaN,151,151.0,0,0,...,0,0,0,1,69,83,150,NaN,NaN,NaN
39684,1958,ML1,NL,aaronha01,153.0,NaN,153,153.0,0,0,...,0,0,0,0,39,120,153,NaN,NaN,NaN
40307,1959,ML1,NL,aaronha01,154.0,NaN,154,154.0,0,0,...,0,5,0,0,13,144,152,NaN,NaN,NaN

In [11]:
appearences.groupby('player_id').sum()

,year,g_all,gs,g_batting,g_defense,g_p,g_c,g_1b,g_2b,g_3b,g_ss,g_lf,g_cf,g_rf,g_of,g_dh,g_ph,g_pr
player_id,,,,,,,,,,,,,,,,,,
aardsda01,18084,331.0,0.0,139,331.0,331,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
aaronha01,45195,3298.0,288.0,3298,3057.0,0,0,210,43,7,0,313,293,2184,2760,196.0,46.0,0.0
aaronto01,13768,437.0,NaN,437,437.0,0,0,232,7,10,0,136,1,2,138,NaN,NaN,NaN
aasedo01,25786,448.0,0.0,81,448.0,448,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
abadan01,6010,15.0,4.0,15,9.0,0,0,8,0,0,0,0,0,1,1,0.0,7.0,1.0
abadfe01,12075,258.0,6.0,131,258.0,258,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
abadijo01,3750,12.0,NaN,12,12.0,0,0,12,0,0,0,0,0,0,0,NaN,NaN,NaN
abbated01,19051,855.0,NaN,855,855.0,0,0,0,419,20,388,0,2,1,3,NaN,NaN,NaN
abbeybe01,11365,79.0,NaN,79,79.0,79,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
abbeych01,9475,452.0,NaN,452,452.0,1,0,0,0,0,0,92,185,173,451,NaN,NaN,NaN
abbotda01,1890,3.0,NaN,3,3.0,3,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
abbotfr01,5712,160.0,NaN,160,160.0,0,138,15,0,0,0,0,0,0,0,NaN,NaN,NaN
abbotgl01,23743,243.0,0.0,3,243.0,248,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
abbotje01,9995,233.0,144.0,233,185.0,0,0,0,0,0,0,63,81,55,185,4.0,50.0,9.0
abbotji01,21932,263.0,13.0,18,263.0,263,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
abbotku01,19971,702.0,508.0,702,602.0,0,0,8,173,43,349,32,4,8,43,4.0,107.0,23.0
abbotky01,7974,57.0,19.0,49,57.0,57,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
abbotod01,1910,22.0,NaN,22,22.0,0,0,0,0,0,0,0,21,0,21,NaN,NaN,NaN
abbotpa01,23977,162.0,12.0,16,162.0,162,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
aberal01,15635,168.0,NaN,168,168.0,168,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
abercda01,1871,1.0,NaN,1,1.0,0,0,0,0,0,1,0,0,0,0,NaN,NaN,NaN
abercre01,6021,180.0,96.0,180,134.0,0,0,0,0,0,0,18,115,15,134,0.0,33.0,28.0
abernbi01,1952,1.0,NaN,1,1.0,1,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
abernbr01,10014,232.0,218.0,232,228.0,0,0,0,223,0,0,5,0,0,5,1.0,5.0,6.0
abernte01,5829,7.0,NaN,7,7.0,7,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
abernte02,33409,681.0,NaN,681,681.0,681,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
abernwo01,3893,16.0,NaN,16,16.0,16,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
aberscl01,5844,63.0,NaN,63,63.0,0,0,0,0,0,0,48,0,1,49,NaN,NaN,NaN
ablesha01,5725,14.0,NaN,14,14.0,14,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
abnersh01,13928,392.0,199.0,392,333.0,0,0,0,0,0,0,73,153,120,333,0.0,78.0,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zimmejo02,14084,181.0,177.0,168,178.0,178,0,0,0,0,0,0,0,0,0,0.0,3.0,0.0
zimmero01,1945,27.0,NaN,27,27.0,0,0,25,0,0,0,0,0,1,1,NaN,NaN,NaN
zimmery01,22110,1293.0,1262.0,1293,1259.0,0,0,98,0,1133,1,31,0,0,31,10.0,27.0,0.0
zinkch01,2008,1.0,0.0,0,1.0,1,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN
zinkwa01,1921,2.0,NaN,2,2.0,2,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
zinnfr01,1888,2.0,NaN,2,2.0,0,2,0,0,0,0,0,0,0,0,NaN,NaN,NaN
zinngu01,9565,314.0,NaN,314,314.0,0,0,0,0,0,0,110,98,85,294,NaN,NaN,NaN
zinnji01,9611,76.0,NaN,76,76.0,66,0,0,0,0,0,0,0,2,2,NaN,NaN,NaN
zinsebi01,1944,2.0,NaN,2,2.0,2,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
zinteal01,4006,67.0,6.0,67,17.0,0,1,16,0,0,0,0,0,0,0,1.0,52.0,1.0
zipfebu01,3923,118.0,NaN,118,118.0,0,0,70,0,0,0,23,0,0,23,NaN,NaN,NaN
ziskri01,25701,1453.0,1247.0,1453,931.0,0,0,0,0,0,0,414,0,506,906,456.0,74.0,0.0
zitoba01,30106,434.0,208.0,213,433.0,433,0,0,0,0,0,0,0,0,0,0.0,0.0,1.0
zitzmbi01,13473,406.0,NaN,406,406.0,0,0,5,0,4,9,189,57,46,289,NaN,NaN,NaN
zmiched01,3821,13.0,NaN,13,13.0,13,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
zobribe01,22120,1190.0,1135.0,1190,1153.0,0,0,17,617,8,229,111,34,336,453,24.0,41.0,4.0
zoccope01,2003,20.0,7.0,20,7.0,0,0,0,0,0,0,3,0,4,7,0.0,13.0,0.0
zoldasa01,19480,251.0,NaN,251,251.0,250,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
zoskyed01,9977,44.0,8.0,44,37.0,0,0,0,3,4,30,0,0,0,0,0.0,10.0,1.0
zuberbi01,23307,224.0,NaN,224,224.0,224,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
zuberjo01,3994,68.0,26.0,68,31.0,0,0,26,0,0,0,5,0,0,5,0.0,39.0,0.0
zuletju01,4001,79.0,36.0,79,55.0,0,0,49,0,0,0,6,0,0,6,0.0,37.0,1.0
zumayjo01,10040,171.0,0.0,14,171.0,171,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
zuninmi01,6042,295.0,275.0,295,292.0,0,292,0,0,0,0,0,0,0,0,1.0,4.0,1.0
zupcibo01,9964,319.0,198.0,319,285.0,0,0,1,0,2,0,100,112,96,282,0.0,25.0,34.0
zupofr01,5876,16.0,NaN,16,16.0,0,13,0,0,0,0,0,0,0,0,NaN,NaN,NaN
zuvelpa01,17875,209.0,138.0,209,197.0,0,0,0,55,14,133,0,0,0,0,2.0,14.0,9.0
zuverge01,19551,266.0,NaN,266,266.0,265,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
zwilldu01,7655,366.0,NaN,366,366.0,0,0,3,0,0,0,0,333,5,339,NaN,NaN,NaN
zychto01,2015,13.0,1.0,0,13.0,13,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0